import React, { useState, useEffect } from 'react';
import ConfigPanel from '../components/panels/ConfigPanel';
import MainWorkspace from '../components/panels/MainWorkspace';
import DataPanel from '../components/panels/DataPanel';

const TOOL_TYPES = {
  SELECT: 'select',
  RECTANGLE: 'rectangle',
  POLYGON: 'polygon',
  CIRCLE: 'circle'
};

const Workspace = ({ experimentType, onBack }) => {
  const [videoFile, setVideoFile] = useState(null);
  const [videoInfo, setVideoInfo] = useState(null);
  const [rois, setROIs] = useState([]);
  const [trackingData, setTrackingData] = useState(null);
  const [isTracking, setIsTracking] = useState(false);
  const [trackingId, setTrackingId] = useState(null);
  const [currentTime, setCurrentTime] = useState(0);
  const [currentFrame, setCurrentFrame] = useState(0);
  const [subjectInfo, setSubjectInfo] = useState({
    id: '',
    group: '',
    weight: '',
    notes: ''
  });
  const [timeRange, setTimeRange] = useState({ start: 0, end: 0 });
  const [scaleCalibration, setScaleCalibration] = useState(null);
  const [algorithmParams, setAlgorithmParams] = useState({
    mog2History: 500,
    mog2VarThreshold: 50,
    minArea: 100,
    maxArea: 10000,
    mouseType: 'auto'
  });
  
  const [activeTool, setActiveTool] = useState(TOOL_TYPES.SELECT);
  const [history, setHistory] = useState([]);
  const [calibrationMode, setCalibrationMode] = useState(false);
  const [calibrationPoints, setCalibrationPoints] = useState([]);

  const [arenaConfig, setArenaConfig] = useState({
    enabled: false,
    arena: null,
    centerRatio: 30,
    showCorners: false,
    cornerRatio: 10
  });
  
  const [showResultsModal, setShowResultsModal] = useState(false);
  const [experiments, setExperiments] = useState([]);
  const [selectedExperiment, setSelectedExperiment] = useState(null);
  const [loadingExperiments, setLoadingExperiments] = useState(false);

  useEffect(() => {
    if (arenaConfig.arena && arenaConfig.enabled && videoInfo) {
      const arena = arenaConfig.arena;

      // arena is normalized (0~1), convert to video pixel coordinates
      const arenaX = arena.x * videoInfo.width;
      const arenaY = arena.y * videoInfo.height;
      const arenaWidth = arena.width * videoInfo.width;
      const arenaHeight = arena.height * videoInfo.height;

      const centerRatio = arenaConfig.centerRatio / 100;
      const centerWidth = arenaWidth * centerRatio;
      const centerHeight = arenaHeight * centerRatio;
      const centerX = arenaX + (arenaWidth - centerWidth) / 2;
      const centerY = arenaY + (arenaHeight - centerHeight) / 2;

      const centerZone = {
        id: 'center-zone',
        name: '中心区',
        type: 'rectangle',
        x: centerX,
        y: centerY,
        width: centerWidth,
        height: centerHeight,
        color: 'hsl(210, 70%, 50%)',
        isAutoGenerated: true,
        parentArena: arena.id
      };

      const cornerSize = Math.min(arenaWidth, arenaHeight) * (arenaConfig.cornerRatio / 100);
      const corners = arenaConfig.showCorners ? [
        {
          id: 'corner-tl',
          name: '左上角',
          type: 'rectangle',
          x: arenaX,
          y: arenaY,
          width: cornerSize,
          height: cornerSize,
          color: 'hsl(120, 70%, 50%)',
          isAutoGenerated: true,
          parentArena: arena.id
        },
        {
          id: 'corner-tr',
          name: '右上角',
          type: 'rectangle',
          x: arenaX + arenaWidth - cornerSize,
          y: arenaY,
          width: cornerSize,
          height: cornerSize,
          color: 'hsl(120, 70%, 50%)',
          isAutoGenerated: true,
          parentArena: arena.id
        },
        {
          id: 'corner-bl',
          name: '左下角',
          type: 'rectangle',
          x: arenaX,
          y: arenaY + arenaHeight - cornerSize,
          width: cornerSize,
          height: cornerSize,
          color: 'hsl(120, 70%, 50%)',
          isAutoGenerated: true,
          parentArena: arena.id
        },
        {
          id: 'corner-br',
          name: '右下角',
          type: 'rectangle',
          x: arenaX + arenaWidth - cornerSize,
          y: arenaY + arenaHeight - cornerSize,
          width: cornerSize,
          height: cornerSize,
          color: 'hsl(120, 70%, 50%)',
          isAutoGenerated: true,
          parentArena: arena.id
        }
      ] : [];

      const autoGeneratedROIs = [centerZone, ...corners];
      setROIs(prevROIs => {
        const userROIs = prevROIs.filter(roi => !roi.isAutoGenerated);
        return [...userROIs, ...autoGeneratedROIs];
      });
    }
  }, [arenaConfig, videoInfo]);

  const handleArenaChange = (newArenaConfig) => {
    setArenaConfig(newArenaConfig);
  };

  const handleToolChange = (tool) => {
    setActiveTool(tool);
  };

  const handleUndo = () => {
    if (history.length > 0) {
      const newHistory = [...history];
      const previousState = newHistory.pop();
      setHistory(newHistory);
      setROIs(previousState);
    }
  };

  const handleClear = () => {
    setHistory([...history, rois]);
    setROIs([]);
  };

  const handleCalibrationClick = (point) => {
    if (calibrationPoints.length < 2) {
      setCalibrationPoints([...calibrationPoints, point]);
    }
  };

  const handleCalibrationComplete = (length) => {
    if (calibrationPoints.length === 2 && length) {
      const pixelDistance = Math.sqrt(
        Math.pow(calibrationPoints[1].x - calibrationPoints[0].x, 2) +
        Math.pow(calibrationPoints[1].y - calibrationPoints[0].y, 2)
      );
      const pixelsPerCm = pixelDistance / parseFloat(length);
      setScaleCalibration({
        pixelsPerCm,
        points: calibrationPoints,
        realLength: parseFloat(length)
      });
      setCalibrationMode(false);
      setCalibrationPoints([]);
    }
  };

  const handleViewResults = async () => {
    setShowResultsModal(true);
    setLoadingExperiments(true);
    
    try {
      const res = await fetch('http://localhost:5000/api/experiments');
      const data = await res.json();
      
      if (data.success) {
        setExperiments(data.experiments || []);
      }
    } catch (error) {
      console.error('Failed to fetch experiments:', error);
    } finally {
      setLoadingExperiments(false);
    }
  };

  const handleSelectExperiment = async (experiment) => {
    try {
      const res = await fetch(`http://localhost:5000/api/experiments/${experiment.experiment_id}`);
      const data = await res.json();
      
      if (data.success) {
        setSelectedExperiment({
          ...data.experiment,
          trajectory: data.trajectory
        });
      }
    } catch (error) {
      console.error('Failed to fetch experiment details:', error);
    }
  };

  const handleBackToList = () => {
    setSelectedExperiment(null);
  };

  const handleCloseModal = () => {
    setShowResultsModal(false);
    setSelectedExperiment(null);
    setExperiments([]);
  };

  return (
    <div className="workspace">
      <header className="workspace-header">
        <div className="header-left">
          <button className="btn-back" onClick={onBack}>
            ← 返回
          </button>
          <div className="experiment-info">
            <span className="experiment-icon">{experimentType.icon}</span>
            <span className="experiment-name">{experimentType.name}</span>
            <span className="experiment-name-en">{experimentType.nameEn}</span>
          </div>
        </div>
        <div className="header-actions">
          <button className="btn btn-secondary" onClick={handleViewResults}>查看结果</button>
          <button className="btn btn-secondary">保存项目</button>
          <button className="btn btn-primary">导出报告</button>
        </div>
      </header>
      
      <div className="workspace-content">
        <div className="panel panel-left">
          <ConfigPanel
            experimentType={experimentType}
            subjectInfo={subjectInfo}
            setSubjectInfo={setSubjectInfo}
            videoFile={videoFile}
            setVideoFile={setVideoFile}
            videoInfo={videoInfo}
            setVideoInfo={setVideoInfo}
            timeRange={timeRange}
            setTimeRange={setTimeRange}
            scaleCalibration={scaleCalibration}
            setScaleCalibration={setScaleCalibration}
            rois={rois}
            setROIs={setROIs}
            algorithmParams={algorithmParams}
            setAlgorithmParams={setAlgorithmParams}
            activeTool={activeTool}
            onToolChange={handleToolChange}
            onUndo={handleUndo}
            onClear={handleClear}
            canUndo={history.length > 0}
            calibrationMode={calibrationMode}
            setCalibrationMode={setCalibrationMode}
            calibrationPoints={calibrationPoints}
            setCalibrationPoints={setCalibrationPoints}
            onCalibrationComplete={handleCalibrationComplete}
            arenaConfig={arenaConfig}
            onArenaChange={handleArenaChange}
          />
        </div>
        
        <div className="panel panel-center">
          <MainWorkspace
            videoFile={videoFile}
            videoInfo={videoInfo}
            rois={rois}
            setROIs={setROIs}
            trackingData={trackingData}
            setTrackingData={setTrackingData}
            isTracking={isTracking}
            setIsTracking={setIsTracking}
            trackingId={trackingId}
            setTrackingId={setTrackingId}
            currentTime={currentTime}
            setCurrentTime={setCurrentTime}
            currentFrame={currentFrame}
            setCurrentFrame={setCurrentFrame}
            scaleCalibration={scaleCalibration}
            setScaleCalibration={setScaleCalibration}
            timeRange={timeRange}
            algorithmParams={algorithmParams}
            activeTool={activeTool}
            onToolChange={handleToolChange}
            onUndo={handleUndo}
            onClear={handleClear}
            history={history}
            setHistory={setHistory}
            calibrationMode={calibrationMode}
            calibrationPoints={calibrationPoints}
            onCalibrationClick={handleCalibrationClick}
            arenaConfig={arenaConfig}
            onArenaChange={handleArenaChange}
            subjectInfo={subjectInfo}
          />
        </div>
        
        <div className="panel panel-right">
          <DataPanel
            experimentType={experimentType}
            trackingData={trackingData}
            rois={rois}
            currentTime={currentTime}
            currentFrame={currentFrame}
            isTracking={isTracking}
            subjectInfo={subjectInfo}
            scaleCalibration={scaleCalibration}
            videoInfo={videoInfo}
            arenaConfig={arenaConfig}
            trackingId={trackingId}
          />
        </div>
      </div>

      {showResultsModal && (
        <div className="results-modal-overlay" onClick={handleCloseModal}>
          <div className="results-modal" onClick={(e) => e.stopPropagation()}>
            <div className="modal-header">
              <h3>已分析的受试体</h3>
              <div className="modal-header-actions">
                <button 
                  className="clear-btn"
                  onClick={async () => {
                    if (window.confirm('确定要清除所有实验数据吗？此操作不可恢复。')) {
                      try {
                        const res = await fetch('http://localhost:5000/api/experiments/clear', {
                          method: 'POST'
                        });
                        const data = await res.json();
                        if (data.success) {
                          setExperiments([]);
                          setSelectedExperiment(null);
                        }
                      } catch (error) {
                        console.error('Failed to clear experiments:', error);
                      }
                    }
                  }}
                >
                  清除所有数据
                </button>
                <button className="close-btn" onClick={handleCloseModal}>×</button>
              </div>
            </div>
            
            <div className="modal-body">
              <div className="modal-left">
                {loadingExperiments ? (
                  <div className="loading-state">
                    <p>加载中...</p>
                  </div>
                ) : experiments.length === 0 ? (
                  <div className="empty-state">
                    <p>暂无分析数据</p>
                    <p className="hint">完成追踪分析后，数据将显示在这里</p>
                  </div>
                ) : (
                  <div className="experiments-list">
                    {experiments.map((exp, index) => {
                      const isSelected = selectedExperiment && 
                        (exp.experiment_id && selectedExperiment.experiment_id === exp.experiment_id);
                      
                      return (
                        <div 
                          key={exp.experiment_id || index} 
                          className={`experiment-item ${isSelected ? 'active' : ''}`}
                          onClick={() => handleSelectExperiment(exp)}
                        >
                        <div className="exp-info">
                          <div className="exp-id">受试体: {exp.subject_id || '未知'}</div>
                          <div className="exp-type">{exp.experiment_type || '行为分析'}</div>
                        </div>
                        <div className="exp-meta">
                          <span className="exp-time">
                            {exp.created_at ? new Date(exp.created_at).toLocaleString('zh-CN') : '未知时间'}
                          </span>
                          <span className="exp-points">
                            {exp.trajectory_count || 0} 个轨迹点
                          </span>
                        </div>
                      </div>
                      );
                    })}
                  </div>
                )}
              </div>
              
              <div className="modal-right">
                {!selectedExperiment ? (
                  <div className="no-selection">
                    <p>请从左侧列表中选择一个受试体查看详情</p>
                  </div>
                ) : (
                  <div className="experiment-detail">
                    <div className="detail-section">
                      <h4>分析指标</h4>
                      <div className="metrics-detail-grid">
                        <div className="metric-detail-item">
                          <span className="metric-label">总运动距离</span>
                          <span className="metric-value">
                            {selectedExperiment.metrics?.total_distance?.toFixed(1) || '-'} 
                            <span className="metric-unit">cm</span>
                          </span>
                          <span className="metric-range">参考: 100-500 cm</span>
                        </div>
                        <div className="metric-detail-item">
                          <span className="metric-label">平均速度</span>
                          <span className="metric-value">
                            {selectedExperiment.metrics?.avg_speed?.toFixed(1) || '-'}
                            <span className="metric-unit">cm/s</span>
                          </span>
                          <span className="metric-range">参考: 5-20 cm/s</span>
                        </div>
                        <div className="metric-detail-item">
                          <span className="metric-label">中心区时间</span>
                          <span className="metric-value">
                            {selectedExperiment.metrics?.center_time?.toFixed(1) || '-'}
                            <span className="metric-unit">s</span>
                          </span>
                          <span className="metric-range">参考: 10-60 s</span>
                        </div>
                        <div className="metric-detail-item">
                          <span className="metric-label">穿越次数</span>
                          <span className="metric-value">
                            {selectedExperiment.metrics?.center_entries || 0}
                            <span className="metric-unit">次</span>
                          </span>
                          <span className="metric-range">参考: 3-15 次</span>
                        </div>
                      </div>
                    </div>

                    <div className="detail-section">
                      <h4>轨迹图</h4>
                      <div className="detail-trajectory">
                        {selectedExperiment.trajectory && selectedExperiment.trajectory.length > 0 ? (
                          <canvas
                            ref={(canvas) => {
                              if (canvas && selectedExperiment.trajectory) {
                                const ctx = canvas.getContext('2d');
                                const width = 350;
                                const height = 350;
                                canvas.width = width;
                                canvas.height = height;
                                
                                ctx.fillStyle = '#1a1a2e';
                                ctx.fillRect(0, 0, width, height);
                                
                                const videoInfo = selectedExperiment.video_info || {};
                                const videoWidth = videoInfo.width || 640;
                                const videoHeight = videoInfo.height || 480;
                                const scale = Math.min(width / videoWidth, height / videoHeight);
                                
                                const trajectory = selectedExperiment.trajectory;
                                ctx.strokeStyle = '#4facfe';
                                ctx.lineWidth = 2;
                                ctx.beginPath();
                                
                                trajectory.forEach((point, i) => {
                                  const x = point.x * scale;
                                  const y = point.y * scale;
                                  if (i === 0) {
                                    ctx.moveTo(x, y);
                                  } else {
                                    ctx.lineTo(x, y);
                                  }
                                });
                                ctx.stroke();
                                
                                if (trajectory.length > 0) {
                                  const start = trajectory[0];
                                  const end = trajectory[trajectory.length - 1];
                                  
                                  ctx.fillStyle = '#00ff00';
                                  ctx.beginPath();
                                  ctx.arc(start.x * scale, start.y * scale, 5, 0, Math.PI * 2);
                                  ctx.fill();
                                  
                                  ctx.fillStyle = '#ff0000';
                                  ctx.beginPath();
                                  ctx.arc(end.x * scale, end.y * scale, 5, 0, Math.PI * 2);
                                  ctx.fill();
                                }
                              }
                            }}
                            style={{ maxWidth: '100%', height: 'auto' }}
                          />
                        ) : (
                          <p className="no-data">暂无轨迹数据</p>
                        )}
                      </div>
                    </div>

                    <div className="detail-section">
                      <h4>热力图</h4>
                      <div className="detail-heatmap">
                        <ExperimentHeatmap experimentId={selectedExperiment.id} />
                      </div>
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      )}

      <style>{`
        .results-modal-overlay {
          position: fixed;
          top: 0;
          left: 0;
          right: 0;
          bottom: 0;
          background: rgba(0, 0, 0, 0.8);
          display: flex;
          justify-content: center;
          align-items: center;
          z-index: 1000;
          padding: 20px;
        }
        
        .results-modal {
          background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
          border-radius: 16px;
          width: 100%;
          max-width: 1200px;
          max-height: 90vh;
          overflow: hidden;
          display: flex;
          flex-direction: column;
          box-shadow: 0 20px 60px rgba(0, 0, 0, 0.5);
        }
        
        .modal-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          padding: 20px 24px;
          border-bottom: 1px solid rgba(255, 255, 255, 0.1);
          flex-shrink: 0;
        }
        
        .modal-header h3 {
          margin: 0;
          color: #fff;
          font-size: 20px;
        }
        
        .modal-header-actions {
          display: flex;
          align-items: center;
          gap: 12px;
        }
        
        .clear-btn {
          background: rgba(255, 77, 77, 0.1);
          border: 1px solid rgba(255, 77, 77, 0.3);
          color: #ff4d4d;
          font-size: 13px;
          padding: 6px 12px;
          border-radius: 4px;
          cursor: pointer;
          transition: all 0.2s;
        }
        
        .clear-btn:hover {
          background: rgba(255, 77, 77, 0.2);
          border-color: rgba(255, 77, 77, 0.5);
        }
        
        .close-btn {
          background: none;
          border: none;
          color: #888;
          font-size: 28px;
          cursor: pointer;
          padding: 0;
          width: 32px;
          height: 32px;
          display: flex;
          align-items: center;
          justify-content: center;
          border-radius: 50%;
          transition: all 0.2s;
        }
        
        .close-btn:hover {
          background: rgba(255, 255, 255, 0.1);
          color: #fff;
        }
        
        .modal-body {
          flex: 1;
          display: flex;
          overflow: hidden;
        }
        
        .modal-left {
          width: 320px;
          border-right: 1px solid rgba(255, 255, 255, 0.1);
          overflow-y: auto;
          flex-shrink: 0;
        }
        
        .modal-right {
          flex: 1;
          overflow-y: auto;
          padding: 24px;
        }
        
        .loading-state, .empty-state, .no-selection {
          display: flex;
          flex-direction: column;
          justify-content: center;
          align-items: center;
          height: 100%;
          text-align: center;
          color: #888;
          padding: 40px 20px;
        }
        
        .empty-state .hint, .no-selection p {
          font-size: 12px;
          color: #666;
          margin-top: 8px;
        }
        
        .experiments-list {
          padding: 12px;
        }
        
        .experiment-item {
          background: rgba(255, 255, 255, 0.05);
          border: 1px solid rgba(255, 255, 255, 0.1);
          border-radius: 12px;
          padding: 16px;
          cursor: pointer;
          transition: all 0.2s;
          margin-bottom: 8px;
        }
        
        .experiment-item:hover {
          background: rgba(255, 255, 255, 0.1);
          border-color: rgba(79, 172, 254, 0.3);
        }
        
        .experiment-item.active {
          background: rgba(79, 172, 254, 0.15);
          border-color: rgba(79, 172, 254, 0.5);
        }
        
        .exp-info {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 8px;
        }
        
        .exp-id {
          font-size: 14px;
          font-weight: 600;
          color: #fff;
        }
        
        .exp-type {
          font-size: 11px;
          color: #4facfe;
          background: rgba(79, 172, 254, 0.1);
          padding: 3px 10px;
          border-radius: 10px;
        }
        
        .exp-meta {
          display: flex;
          gap: 12px;
          font-size: 11px;
          color: #888;
        }
        
        .experiment-detail {
          display: flex;
          flex-direction: column;
          gap: 20px;
        }
        
        .detail-section {
          background: rgba(255, 255, 255, 0.03);
          border-radius: 12px;
          padding: 20px;
        }
        
        .detail-section h4 {
          margin: 0 0 16px 0;
          color: #fff;
          font-size: 15px;
          border-bottom: 1px solid rgba(255, 255, 255, 0.1);
          padding-bottom: 12px;
        }
        
        .metrics-detail-grid {
          display: grid;
          grid-template-columns: repeat(2, 1fr);
          gap: 16px;
        }
        
        .metric-detail-item {
          display: flex;
          flex-direction: column;
          gap: 4px;
        }
        
        .metric-detail-item .metric-label {
          font-size: 12px;
          color: #888;
        }
        
        .metric-detail-item .metric-value {
          font-size: 22px;
          font-weight: 600;
          color: #fff;
        }
        
        .metric-detail-item .metric-unit {
          font-size: 13px;
          color: #666;
          margin-left: 4px;
        }
        
        .metric-detail-item .metric-range {
          font-size: 11px;
          color: #666;
        }
        
        .detail-trajectory, .detail-heatmap {
          display: flex;
          justify-content: center;
          align-items: center;
          min-height: 200px;
          background: #1a1a2e;
          border-radius: 8px;
          overflow: hidden;
        }
        
        .no-data {
          color: #666;
          padding: 40px;
        }
        
        @media (max-width: 900px) {
          .results-modal {
            max-width: 100%;
            max-height: 100vh;
            border-radius: 0;
          }
          
          .modal-body {
            flex-direction: column;
          }
          
          .modal-left {
            width: 100%;
            max-height: 300px;
            border-right: none;
            border-bottom: 1px solid rgba(255, 255, 255, 0.1);
          }
          
          .metrics-detail-grid {
            grid-template-columns: 1fr;
          }
        }
      `}</style>
    </div>
  );
};

const ExperimentHeatmap = ({ experimentId }) => {
  const [heatmapImage, setHeatmapImage] = React.useState(null);
  const [loading, setLoading] = React.useState(true);

  React.useEffect(() => {
    const fetchHeatmap = async () => {
      if (!experimentId) return;
      
      setLoading(true);
      try {
        const res = await fetch(`http://localhost:5000/api/experiments/${experimentId}/heatmap`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            bandwidth: 15,
            scaleMode: 'auto',
            maxValue: 10
          })
        });
        const data = await res.json();
        
        if (data.success) {
          setHeatmapImage(data.heatmap);
        }
      } catch (error) {
        console.error('Failed to fetch experiment heatmap:', error);
      } finally {
        setLoading(false);
      }
    };

    fetchHeatmap();
  }, [experimentId]);

  return (
    <div className="experiment-heatmap-container">
      {loading ? (
        <div className="heatmap-loading">
          <p>加载热力图中...</p>
        </div>
      ) : heatmapImage ? (
        <img 
          src={`data:image/png;base64,${heatmapImage}`} 
          alt="Experiment Heatmap"
          style={{ maxWidth: '100%', maxHeight: '300px', objectFit: 'contain' }}
        />
      ) : (
        <div className="heatmap-no-data">
          <p>暂无热力图数据</p>
        </div>
      )}
      
      <style>{`
        .experiment-heatmap-container {
          display: flex;
          justify-content: center;
          align-items: center;
          min-height: 200px;
          background: #1a1a2e;
          border-radius: 8px;
          overflow: hidden;
        }
        .heatmap-loading, .heatmap-no-data {
          text-align: center;
          color: #666;
          padding: 40px;
        }
      `}</style>
    </div>
  );
};

export default Workspace;
